#
# Copyright (C) 2021-2024 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/xuanying/sy910

TARGET_BOARD_PLATFORM_PRODUCT := atv

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a53
TARGET_CPU_SMP := true

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a53

PRODUCT_KERNEL_VERSION := 5.10

BOARD_KERNEL_CMDLINE := androidboot.boot_devices=ffbf0000.mmc
PRODUCT_KERNEL_ARCH = arm64
PRODUCT_KERNEL_DTS = rk3528-demo4-ddr4-v10
PRODUCT_KERNEL_CONFIG = rockchip_defconfig

PRODUCT_BOOT_DEVICE := ffbf0000.mmc

## Bootloader
TARGET_BOOTLOADER_BOARD_NAME := sy910

## DTB
TARGET_DTB_NAME := rk3528-demo4-ddr4-v10
TARGET_DTBO_NAME := sy910_overlay

## HIDL
DEVICE_MANIFEST_FILE += $(DEVICE_PATH)/manifest.xml

## Partitions
BOARD_SUPER_PARTITION_SIZE := 1677721600

## Properties
TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop

## SELinux
SELINUX_IGNORE_NEVERALLOWS := true
BOARD_VENDOR_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/vendor

## Dex Pre-Opt
WITH_DEXPREOPT_DEBUG_INFO := false
